---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
  namespace: {{ .Values.clusterIssuer.namespace }}
spec:
  acme:
    email: {{ .Values.certManager.email }}
    server: {{ .Values.certManager.server }}
    privateKeySecretRef:
      name: {{ .Values.certManager.privateKeySecretRef.name }}
    solvers:
      # https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
      - dns01:
          cloudflare:
            email: {{ .Values.certManager.email }}
            apiTokenSecretRef:
              name: {{ .Values.certManager.apiTokenSecretRef.name }}
              key: {{ .Values.certManager.apiTokenSecretRef.key }}
