---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  selector:
    istio: {{ .Values.gateway.selector.istio }}
  servers:
    - port:
        number: {{ .Values.gateway.http.port }}
        name: {{ .Values.gateway.http.name }}
        protocol: HTTP
      hosts:
        - {{ .Values.domain.name | quote }}
    - port:
        number: {{ .Values.gateway.https.port }}
        name: {{ .Values.gateway.https.name }}
        protocol: HTTPS
      hosts:
        - {{ .Values.domain.name | quote }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.gateway.https.credentialName }}
