---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.secret.namespace }}
type: {{ .Values.secret.type }}
stringData:
  api-token: {{ .Values.secret.apiToken }}
