---
- name: Create boutique application
  hosts: gcloud_boutique
  gather_facts: false
  tasks:
    - name: Include role for app creation
      ansible.builtin.include_role:
        name: "gcloud/application"
      vars:
        mode: create
