---
- name: Delete boutique application
  hosts: gcloud_boutique
  gather_facts: false
  tasks:
    - name: Include role for app deletion
      ansible.builtin.include_role:
        name: "gcloud/application"
      vars:
        mode: delete
