########################################################################################
# Project: 
#   Managed Kubernetes Services: A Comparison of AKS, EKS and GKE
#
# Author:  
#   Michał Ziemianek
#
# Description:
#   The project focuses on deploying and benchmarking
#   a microservices-based application using Kubernetes and cloud-native technologies
#   (Terraform, Ansible, Helm, Prometheus, Grafana, K6).
#
# License:
#   Apache 2.0
#
# Notes:
#   - This code is intended for educational and research purposes.
#   - Ensure proper configuration of cloud resources before execution.
#
# © 2025 Michał Ziemianek. All rights reserved.
########################################################################################
---

- name: "{{ service_name }} | Apply Terraform changes using the saved plan file"
  environment: "{{ tf_environment }}"
  ansible.builtin.command:
    cmd: terraform -chdir="{{ tf_directory }}" apply -input=false -no-color -auto-approve -var-file="{{ tf_vars_file_path }}" "{{ tf_plan_file_path }}"
  register: tf_apply_output
  changed_when: tf_apply_output.rc != 0

- name: "{{ service_name }} | Display Terraform apply result"
  ansible.builtin.debug:
    msg: "{{ tf_apply_output.stdout }}"
