---
- name: Apply Terraform changes using the saved plan file
  ansible.builtin.command:
    cmd: terraform apply -input=false tfplan
  register: terraform_apply_result

- name: Display Terraform apply result
  ansible.builtin.debug:
    msg: "{{ terraform_apply_result.stdout }}"
  when: terraform_apply_result.rc == 0

- name: Delete TF plan file
  ansible.builtin.file:
    path: "{{ tf_plan_file }}"
    state: absent
