---

- name: Run Terraform destroy
  environment: "{{ tf_environment }}"
  block:
    - name: Select workspace
      ansible.builtin.command: 
        cmd: terraform -chdir="{{ tf_directory }}" workspace select "{{ tf_workspace }}" -no-color
      register: tf_select_workspace_output
      changed_when: tf_select_workspace_output.rc != 0

    - name: Destroy Terraform resources
      ansible.builtin.command: 
        cmd: terraform -chdir="{{ tf_directory }}" destroy -auto-approve -no-color -var-file="{{ tf_vars_file_path }}"
      register: tf_destroy_output
      changed_when: tf_destroy_output.rc != 0

    - name: Display Terraform destroy result
      ansible.builtin.debug:
        msg: "{{ tf_destroy_output.stdout }}"

- name: Delete files
  ansible.builtin.file:
    path: "{{ file }}"
    state: absent
  loop:
    - "{{ tf_plan_file_path }}"
    - "{{ tf_vars_file_path }}"
  loop_control:
    loop_var: file
