########################################################################################
# Project: 
#   Managed Kubernetes Services: A Comparison of AKS, EKS and GKE
#
# Author:  
#   Michał Ziemianek
#
# Description:
#   The project focuses on deploying and benchmarking
#   a microservices-based application using Kubernetes and cloud-native technologies
#   (Terraform, Ansible, Helm, Prometheus, Grafana, K6).
#
# License:
#   Apache 2.0
#
# Notes:
#   - This code is intended for educational and research purposes.
#   - Ensure proper configuration of cloud resources before execution.
#
# © 2025 Michał Ziemianek. All rights reserved.
########################################################################################
---

- name: "{{ service_name }} | Fail if this role doesn't have a parent role"
  ansible.builtin.fail:
    msg: "This role can only be run from within another role."
  when: ansible_parent_role_names is not defined

- name: "{{ service_name }} | Fail if operation is not valid"
  ansible.builtin.fail:
    msg: "Invalid operation: '{{ operation }}'. Allowed values are 'init', 'apply' or 'destroy'."
  when: operation not in ['init', 'apply', 'destroy']

- name: "{{ service_name }} | Execute Terraform operation"
  ansible.builtin.include_tasks: "{{ operation }}.yaml"
