---
# Wrapped in a block to pass env variables
# https://github.com/ansible/ansible/issues/53626
- name: "{{ service_name }} | Block wrapper"
  environment:
    KUBECONFIG: "{{ k8s_kubeconfig_path }}"
  block:
    - name: "{{ service_name }} | Get kubeconfig for the '{{ cluster_name }}' cluster"
      ansible.builtin.command: >
        gcloud container clusters get-credentials {{ cluster_name }}
        --project {{ gcloud_project_id }}
        --region {{ gcloud_region }}
      changed_when: true

    - name: "{{ service_name }} | Get Cluster Ingress IP Address"
      ansible.builtin.command: |
        kubectl get svc -n istio-ingress -o jsonpath='{.items[*].status.loadBalancer.ingress[*].ip}'
      register: cluster_ingress_ip_address
      changed_when: true

    - name: "{{ service_name }} | Print IP Address"
      ansible.builtin.debug:
        msg: "Cluster Ingress IP Address: {{ cluster_ingress_ip_address.stdout }}"
  always:
    - name: "{{ service_name }} | Clean kubeconfig"
      ansible.builtin.file:
        path: "{{ k8s_kubeconfig_path }}"
        state: absent

- name: "{{ service_name }} | Create DNS Record"
  community.general.cloudflare_dns:
    zone: "{{ dns_root_domain_name }}"
    record: "{{ dns_domain_name }}"
    type: A
    value: "{{ cluster_ingress_ip_address.stdout }}"
    api_token: "{{ vault_cloudflare_token }}"
    state: present
