---
prometheusOperator:
  nodeSelector:
    role: monitoring
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"

prometheus:
  prometheusSpec:
    nodeSelector:
      role: monitoring
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      role: monitoring
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"

grafana:
  adminUser: "{{ vault_grafana_admin_username }}"
  adminPassword: "{{ vault_grafana_admin_password }}"
  nodeSelector:
    role: monitoring
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"

kube-state-metrics:
  nodeSelector:
    role: monitoring
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"
