---

# TODO: make this a loop?
prometheusOperator:
  nodeSelector:
    role: "{{ monitoring_namespace }}"
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "{{ monitoring_namespace }}"
      effect: "NoSchedule"

prometheus:
  prometheusSpec:
    nodeSelector:
      role: "{{ monitoring_namespace }}"
    serviceMonitorSelector: {}
    podMonitorSelector: {}
    probeSelector: {}
    ruleSelector: {}
    serviceMonitorNamespaceSelector: {}
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "{{ monitoring_namespace }}"
        effect: "NoSchedule"

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      role: "{{ monitoring_namespace }}"
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "{{ monitoring_namespace }}"
        effect: "NoSchedule"

kube-state-metrics:
  nodeSelector:
    role: "{{ monitoring_namespace }}"
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "{{ monitoring_namespace }}"
      effect: "NoSchedule"


# TODO: add dashboards from files/dashboards
grafana:
  adminUser: "{{ vault_grafana_admin_username }}"
  adminPassword: "{{ vault_grafana_admin_password }}"
  nodeSelector:
    role: "{{ monitoring_namespace }}"
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "{{ monitoring_namespace }}"
      effect: "NoSchedule"
