---
- name: Create VPC in GCP
  hosts: gcloud_common
  gather_facts: false
  tasks:
    - name: Include role for VPC creation
      ansible.builtin.include_role:
        name: gcloud/vpc
      vars:
        mode: create
