---
- name: Delete VPC in GCP
  hosts: gcloud_common
  gather_facts: false
  tasks:
    - name: Include role for VPC deletion
      ansible.builtin.include_role:
        name: gcloud/vpc
      vars:
        mode: delete
