# Terraform variables
tf_directory: "{{ ansible_parent_role_paths[0] }}/files/terraform"
tf_backend_config_file: "{{ cloud_name }}.{{ tf_backend_type }}.tfbackend"
tf_workspace: "{{ cloud_name }}_{{ service_name }}"
tf_vars_template_file_path: "{{ ansible_parent_role_paths[0] }}/templates/tfvars.j2"
tf_vars_file_path: "/tmp/{{ tf_workspace }}.tfvars"
tf_plan_file_path: "/tmp/{{ tf_workspace }}.tfplan"

tf_environment:
  GOOGLE_CREDENTIALS: "{{ vault_gcloud_credentials }}"
