########################################################################################
# Project: 
#   Managed Kubernetes Services: A Comparison of AKS, EKS and GKE
#
# Author:  
#   Michał Ziemianek
#
# Description:
#   The project focuses on deploying and benchmarking
#   a microservices-based application using Kubernetes and cloud-native technologies
#   (Terraform, Ansible, Helm, Prometheus, Grafana, K6).
#
# License:
#   Apache 2.0
#
# Notes:
#   - This code is intended for educational and research purposes.
#   - Ensure proper configuration of cloud resources before execution.
#
# © 2025 Michał Ziemianek. All rights reserved.
########################################################################################

# todo: move this to helm chart?
# ===
# Certificate configuration (self-signed)
certificate:
  name: "istio-ingress-cert"
  namespace: "istio-ingress"
  secretName: "istio-ingress-cert"

# ClusterIssuer configuration - self signed
clusterIssuer:
  name: "selfsigned-cluster-issuer"
  namespace: "istio-ingress"
  selfSigned: true

# Gateway configuration
gateway:
  name: "istio-ingress-gateway"
  namespace: "istio-ingress"
  selector:
    istio: "ingress-gateway"
  http:
    port: 80
    name: "http"
  https:
    port: 443
    name: "https"
    credentialName: "istio-ingress-cert"
# ===

# Virtual Service configuration
virtualService:
  name: "istio-ingress-vs"
  namespace: "istio-ingress"
  gatewayRef: "istio-ingress-gateway"
  hosts:
    - "*"   # akceptuje każdy host, w tym IP load balancera
  routes:
    frontend:
      host: "frontend.{{ app_name }}.svc.cluster.local"
      port: 80
