---

# Wrapped in a block to pass env variables
# https://github.com/ansible/ansible/issues/53626
- name: "{{ service_name }} | Block wrapper"
  environment:
    KUBECONFIG: "{{ k8s_kubeconfig_path }}"
  block:
    - name: "{{ service_name }} | Get kubeconfig for the '{{ cluster_name }}' cluster"
      ansible.builtin.command: >
        gcloud container clusters get-credentials {{ cluster_name }}
        --project {{ gcp_project_id }}
        --region {{ gcp_region }}
      changed_when: true

    - name: Get monitoring node name
      ansible.builtin.command:
        cmd: kubectl get nodes -l role=monitoring -o custom-columns=NAME:.metadata.name --no-headers
      register: monitoring_node_name

    - name: Print monitoring node name
      ansible.builtin.debug:
        msg: "Monitoring node name: {{ monitoring_node_name.stdout }}"

    - name: Set taint for monitoring nodes
      ansible.builtin.command:
        cmd: kubectl taint nodes "{{ monitoring_node_name.stdout }}" dedicated=monitoring:NoSchedule

  always:
    - name: "{{ service_name }} | Clean kubeconfig"
      ansible.builtin.file:
        path: "{{ k8s_kubeconfig_path }}"
        state: absent
