kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: shop
  name: account-shop-viewer-hbawy
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: shop
  name: role-shop-viewer-hbawy
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["chaos-mesh.org"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-shop-viewer-hbawy
  namespace: shop
subjects:
  - kind: ServiceAccount
    name: account-shop-viewer-hbawy
    namespace: shop
roleRef:
  kind: Role
  name: role-shop-viewer-hbawy
  apiGroup: rbac.authorization.k8s.io
