---
- name: Create GKE Cluster
  ansible.builtin.import_playbook: "{{ infra_version }}/gke_cluster/boutique/create.yaml"

- name: Create GKE Cluster Addons
  ansible.builtin.import_playbook: "{{ infra_version }}/gke_cluster_addons/boutique/create.yaml"
