---
# - name: Create GKE Cluster
#   ansible.builtin.import_playbook: gke_cluster/boutique/create.yaml

- name: Create GKE Cluster Addons
  ansible.builtin.import_playbook: gke_cluster_addons/boutique/create.yaml

- name: Create DNS Record in Cloudflare
  ansible.builtin.import_playbook: cloudflare_dns_record/boutique/create.yaml

- name: Create Boutique application
  ansible.builtin.import_playbook: application/boutique/create.yaml
