---
- name: Delete Application
  ansible.builtin.import_playbook: app_manager/boutique/delete.yaml

- name: Delete GKE Cluster Addons
  ansible.builtin.import_playbook: gke_cluster_addons/boutique/delete.yaml

# - name: Delete GKE Cluster
#   ansible.builtin.import_playbook: gke_cluster/boutique/delete.yaml
