---
- name: Delete Boutique Application
  ansible.builtin.import_playbook: application/boutique/delete.yaml

# Commented out to prevent dns propagation delay
# - name: Delete DNS Record in Cloudflare
#   ansible.builtin.import_playbook: cloudflare_dns_record/boutique/delete.yaml

- name: Delete GKE Cluster Addons
  ansible.builtin.import_playbook: gke_cluster_addons/boutique/delete.yaml

- name: Delete GKE Cluster
  ansible.builtin.import_playbook: gke_cluster/boutique/delete.yaml
