---

# Wrapped in a block to pass env variables
# https://github.com/ansible/ansible/issues/53626
- name: "{{ service_name }} | Block wrapper"
  environment:
    KUBECONFIG: "{{ k8s_kubeconfig_path }}"
  block:
    - name: "{{ service_name }} | Get kubeconfig for the '{{ cluster_name }}' cluster"
      # TODO: move resource group to variable
      ansible.builtin.command: >
        az aks get-credentials 
        --resource-group boutique-aks 
        --name {{ cluster_name }} 
        --overwrite-existing
      changed_when: true

    - name: Get monitoring node name
      ansible.builtin.command:
        cmd: kubectl apply -f "{{ role_path }}/files/manifests/hpa.yaml"

  always:
    - name: "{{ service_name }} | Clean kubeconfig"
      ansible.builtin.file:
        path: "{{ k8s_kubeconfig_path }}"
        state: absent
