---
- name: "{{ service_name }} | Run Terraform Init"
  ansible.builtin.include_role:
    name: terraform
  vars:
    operation: init

- name: "{{ service_name }} | Run Terraform Apply"
  ansible.builtin.include_role:
    name: terraform
  vars:
    operation: apply

- name: "{{ service_name }} | Deploy Kubernetes manifests"
  ansible.builtin.include_role:
    name: k8s_manifest
  vars:
    operation: create
    cluster_name: "{{ gke_cluster_name }}" # FIXME: Change gke_cluster_name to cluster_name in grooup vars
