---
- name: Create DNS Record in Cloudflare
  hosts: gcloud_boutique
  gather_facts: false
  tasks:
    - name: Include role for record creation
      ansible.builtin.include_role:
        name: "gcloud/cloudflare_dns_record"
      vars:
        mode: create
