---
- name: "Get kubeconfig for the '{{ gke_cluster_name }}' cluster"
  ansible.builtin.command: >
    gcloud container clusters get-credentials {{ gke_cluster_name }}
    --project {{ gcloud_project_id }}
    --region {{ gcloud_region }}
  changed_when: true

- name: "{{ operation | title }} Kubernetes resources from manifest"
  ansible.builtin.include_tasks: handle_manifest.yaml
  loop: "{{ k8s_manifests }}"
  loop_control:
    loop_var: manifest
