---
- name: Set manifest path
  ansible.builtin.set_fact:
    k8s_manifest_path: "{{ k8s_directory }}/{{ manifest }}"

- name: "{{ operation | title }} {{ manifest }}"
  # no_log: true
  kubernetes.core.k8s:
    state: "{{ k8s_manifest_state }}"
    definition: "{{ lookup('file', '{{ k8s_manifest_path }}') | from_yaml_all }}"
    validate:
      fail_on_error: yes # fail on validation errors
      strict: yes # check for unexpected properties
    # wait: true  # FIXME: Doesnt work with multiple objects in 1 manifest
