apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  commonName: boutique.ziemian.top
  dnsNames:
  - boutique.ziemian.top
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  usages:
    - digital signature
    - key encipherment
    - server auth
  # Disable the default solver behaviors by using Istio Gateway
  # instead of creating k8s Ingress resources
  solvers:
  - http01:
      ingress:
        class: istio