########################################################################################
# Project: 
#   Managed Kubernetes Services: A Comparison of AKS, EKS and GKE
#
# Author:  
#   Michał Ziemianek
#
# Description:
#   The project focuses on deploying and benchmarking
#   a microservices-based application using Kubernetes and cloud-native technologies
#   (Terraform, Ansible, Helm, Prometheus, Grafana, K6).
#
# License:
#   Apache 2.0
#
# Notes:
#   - This code is intended for educational and research purposes.
#   - Ensure proper configuration of cloud resources before execution.
#
# © 2025 Michał Ziemianek. All rights reserved.
########################################################################################
---

cloud_name: azure

azure_location: westeurope
resource_group_name: "{{ app_name }}"

tf_environment:
  ARM_CLIENT_ID: "{{ vault_azure_client_id }}"
  ARM_CLIENT_SECRET: "{{ vault_azure_client_secret }}"
  ARM_TENANT_ID: "{{ vault_azure_tenant_id }}"
  ARM_SUBSCRIPTION_ID: "{{ vault_azure_subscription_id }}"
