---
cloud_name: gcloud
gcloud_region: europe-central2 # Warsaw
gcloud_project_id: "{{ vault_gcloud_project_id }}"
gcloud_vpc_name: magisterka-vpc
gcloud_vpc_cidr: 10.10.0.0/20
gcloud_subnet_name: magisterka-subnet

# Terraform
tf_backend_type: gcs
tf_environment:
  GOOGLE_CREDENTIALS: "{{ vault_gcloud_credentials }}"

# GKE
cluster_name: "{{ app_name }}-gke-cluster"
gke_node_count: 2
gke_node_machine_type: e2-standard-4
gke_node_disk_size: 20
