########################################################################################
# Project: 
#   Managed Kubernetes Services: A Comparison of AKS, EKS and GKE
#
# Author:  
#   Michał Ziemianek
#
# Description:
#   The project focuses on deploying and benchmarking
#   a microservices-based application using Kubernetes and cloud-native technologies
#   (Terraform, Ansible, Helm, Prometheus, Grafana, K6).
#
# License:
#   Apache 2.0
#
# Notes:
#   - This code is intended for educational and research purposes.
#   - Ensure proper configuration of cloud resources before execution.
#
# © 2025 Michał Ziemianek. All rights reserved.
########################################################################################
---

cloud_name: gcloud
app_name: butik
dns_domain_name: "{{ app_name }}-gcp.{{ dns_root_domain_name }}"

# GCP
gcloud_region: europe-central2 # Warsaw
gcloud_project_id: "{{ vault_gcloud_project_id }}"
gcloud_vpc_name: magisterka-vpc
gcloud_vpc_cidr: 10.10.0.0/20
gcloud_subnet_name: magisterka-subnet

# Terraform
tf_backend_type: gcs
tf_environment:
  GOOGLE_CREDENTIALS: "{{ vault_gcloud_credentials }}"

# GKE
cluster_name: "{{ app_name }}-gke-cluster"
gke_node_count: 3
gke_node_machine_type: e2-standard-4
gke_node_disk_size: 20
gke_subnet_cidr: 10.10.0.0/20
gke_subnet_name: "{{ app_name }}-gke-subnet"
