########################################################################################
# Project: 
#   Managed Kubernetes Services: A Comparison of AKS, EKS and GKE
#
# Author:  
#   Michał Ziemianek
#
# Description:
#   The project focuses on deploying and benchmarking
#   a microservices-based application using Kubernetes and cloud-native technologies
#   (Terraform, Ansible, Helm, Prometheus, Grafana, K6).
#
# License:
#   Apache 2.0
#
# Notes:
#   - This code is intended for educational and research purposes.
#   - Ensure proper configuration of cloud resources before execution.
#
# © 2025 Michał Ziemianek. All rights reserved.
########################################################################################
---

_gcp_credentials:
  type: service_account
  project_id:
  private_key_id:
  private_key: |
    -----BEGIN PRIVATE KEY-----

    -----END PRIVATE KEY-----
  client_email:
  client_id:
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://oauth2.googleapis.com/token
  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_x509_cert_url:
  universe_domain: googleapis.com

# ===

vault_gcp_credentials: "{{ _gcp_credentials | to_json }}"
vault_gcp_project_id: "{{ _gcp_credentials.project_id }}"

vault_cloudflare_token:

vault_dns_email:
