- name: "{{ service_name }} | Run Terraform Init"
  ansible.builtin.include_role:
    name: terraform
  vars:
    mode: init

- name: "{{ service_name }} | Run Terraform Apply"
  ansible.builtin.include_role:
    name: terraform
  vars:
    mode: apply
