---
- name: "{{ service_name }} | Render template to {{ rendered_template_path }}"
  ansible.builtin.template:
    src: "{{ template_path }}"
    dest: "{{ rendered_template_path }}"
    mode: '0644'

- name: "{{ service_name }} | Show templating results"
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.template', './{{ template_path }}') }}"

- name: "{{ service_name }} | Cleanup"
  when: save_template | default(false) | bool != true
  ansible.builtin.file:
    src: "{{ rendered_template_path }}"
    state: absent
