kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: shop
  name: role-shop-viewer-hbawy
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["chaos-mesh.org"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
