apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-shop-viewer-hbawy
  namespace: shop
subjects:
  - kind: ServiceAccount
    name: account-shop-viewer-hbawy
    namespace: shop
roleRef:
  kind: Role
  name: role-shop-viewer-hbawy
  apiGroup: rbac.authorization.k8s.io
