---
- name: Delete GKE Cluster Istio Ingress
  hosts: gcloud_boutique
  gather_facts: false
  tasks:
    - name: Include role for cluster addons deletion
      ansible.builtin.include_role:
        name: gcloud/istio_ingress
      vars:
        mode: delete
