apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  selector:
{{ toYaml .Values.gateway.selector | indent 4 }}
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.certificate.secretName }}
    hosts:
{{- range .Values.gateway.hosts }}
    - "{{ . }}"
{{- end }}
