########################################################################################
# Project: 
#   Managed Kubernetes Services: A Comparison of AKS, EKS and GKE
#
# Author:  
#   Michał Ziemianek
#
# Description:
#   The project focuses on deploying and benchmarking
#   a microservices-based application using Kubernetes and cloud-native technologies
#   (Terraform, Ansible, Helm, Prometheus, Grafana, K6).
#
# License:
#   Apache 2.0
#
# Notes:
#   - This code is intended for educational and research purposes.
#   - Ensure proper configuration of cloud resources before execution.
#
# © 2025 Michał Ziemianek. All rights reserved.
########################################################################################
---

app_name: boutique

vpc_name: "{{ app_name }}-vpc"

cluster_name: "{{ app_name }}-k8s-cluster"

k8s_kubeconfig_path: "/tmp/{{ cluster_name }}-kubeconfig"

monitoring_namespace: monitoring
application_namespace: "{{ app_name }}"
