########################################################################################
# Project: 
#   Managed Kubernetes Services: A Comparison of AKS, EKS and GKE
#
# Author:  
#   Michał Ziemianek
#
# Description:
#   The project focuses on deploying and benchmarking
#   a microservices-based application using Kubernetes and cloud-native technologies
#   (Terraform, Ansible, Helm, Prometheus, Grafana, K6).
#
# License:
#   Apache 2.0
#
# Notes:
#   - This code is intended for educational and research purposes.
#   - Ensure proper configuration of cloud resources before execution.
#
# © 2025 Michał Ziemianek. All rights reserved.
########################################################################################
---
app_name: boutique

dns_root_domain_name: ziemian.top
dns_domain_name: "{{ app_name }}-{{ cloud_name }}.{{ dns_root_domain_name }}"

vpc_name: "{{ app_name }}-vpc"

cluster_name: "{{ app_name }}-k8s-cluster"

k8s_kubeconfig_path: "/tmp/{{ cluster_name }}-kubeconfig"

repo_url: https://github.com/ziemianek/mgr-env-prod
