---
- name: "Create {{ app_name | title }} application"
  hosts: gcloud_boutique
  gather_facts: false
  tasks:
    - name: Include role for app management
      ansible.builtin.include_role:
        name: gcloud/app_manager
      vars:
        mode: create
