---
- name: "{{ service_name }} | Run Terraform Init"
  ansible.builtin.include_role:
    name: terraform
  vars:
    operation: init

- name: "{{ service_name }} | Run Terraform Apply"
  ansible.builtin.include_role:
    name: terraform
  vars:
    operation: apply

- name: "{{ service_name }} | Cleanup"
  when: save_template | default(false) == false
  ansible.builtin.file:
    path: "{{ cluster_istio_ingress_rendered_template_path }}"
    state: absent
