---
# todo: refactor this - download file and use k8s_manifests role
# to get rid of the error:
# cert-manager CRDs are not yet installed on the Kubernetes API server"
# this must be installed before installing cert-manager helm chart
# https://stackoverflow.com/questions/78091886/issue-with-cert-manager-installation

# Wrapped in a block to pass env variables
# https://github.com/ansible/ansible/issues/53626
- name: "{{ service_name }} | Get cert-manager CRDs"
  environment:
    KUBECONFIG: "{{ k8s_kubeconfig_path }}"
  block:
    - name: "{{ service_name }} | Create kubeconfig"
      ansible.builtin.command: >
        gcloud container clusters get-credentials {{ cluster_name }}
        --project {{ gcloud_project_id }}
        --region {{ gcloud_region }}
      changed_when: true

    - name: "{{ service_name }} | Kubectl apply cert-manager CRDs"
      ansible.builtin.command: |
        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.17.1/cert-manager.crds.yaml
      changed_when: true
  always:
    - name: "{{ service_name }} | Clean kubeconfig"
      ansible.builtin.file:
        path: "{{ k8s_kubeconfig_path }}"
        state: absent

- name: "{{ service_name }} | Run Terraform Init"
  ansible.builtin.include_role:
    name: terraform
  vars:
    operation: init

- name: "{{ service_name }} | Run Terraform Apply"
  ansible.builtin.include_role:
    name: terraform
  vars:
    operation: apply

- name: "{{ service_name }} | Deploy Kubernetes manifests"
  ansible.builtin.include_role:
    name: k8s_manifest
  vars:
    operation: create
