---
- name: "{{ service_name }} | Render template to {{ rendered_template_path }}"
  ansible.builtin.template:
    src: "{{ cluster_istio_ingress_template_path }}"
    dest: "{{ cluster_istio_ingress_rendered_template_path }}"
    mode: "0644"

- name: "{{ service_name }} | Show templating results"
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.template', '{{ cluster_istio_ingress_rendered_template_path }}') }}"

- name: "{{ service_name }} | Google Cloud GKE Cluster Addons"
  ansible.builtin.include_tasks: "{{ mode }}.yaml"

- name: "{{ service_name }} | Cleanup"
  when: save_template | default(false)
  ansible.builtin.file:
    path: "{{ cluster_istio_ingress_rendered_template_path }}"
    state: absent
