---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-issuer
  namespace: cert-manager
spec:
  acme:
    email: mziemianek3@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      # https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
      - dns01:
          cloudflare:
            email: mziemianek3@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: Z0JdGJk0xU-LXmhs3sc6py7Fl8OOt2g0iP7c_XuR # vault_cloudflare_token

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingress-cert
  namespace: istio-ingress
spec:
  secretName: istio-ingress-cert
  # commonName: boutique.ziemian.top
  issuerRef:
    name: letsencrypt-prod-issuer
    kind: ClusterIssuer
  dnsNames:
    - "boutique.ziemian.top"
---
