---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: istio-ingress-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingress-gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "boutique.ziemian.top"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "boutique.ziemian.top"
      tls:
        mode: SIMPLE
        credentialName: istio-ingress-cert
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: istio-ingress-vs
  namespace: istio-ingress
spec:
  hosts:
    - "boutique.ziemian.top"
  gateways:
    - istio-ingress-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: frontend.boutique.svc.cluster.local
            port:
              number: 80
