---
- name: Delete GKE Cluster
  hosts: gcloud
  gather_facts: false
  tasks:
    - name: Include role for cluster deletion
      ansible.builtin.include_role:
        name: gcloud/gke_cluster
      vars:
        mode: delete
