########################################################################################
# Project: 
#   Managed Kubernetes Services: A Comparison of AKS, EKS and GKE
#
# Author:  
#   Michał Ziemianek
#
# Description:
#   The project focuses on deploying and benchmarking
#   a microservices-based application using Kubernetes and cloud-native technologies
#   (Terraform, Ansible, Helm, Prometheus, Grafana, K6).
#
# License:
#   Apache 2.0
#
# Notes:
#   - This code is intended for educational and research purposes.
#   - Ensure proper configuration of cloud resources before execution.
#
# © 2025 Michał Ziemianek. All rights reserved.
########################################################################################

variable "project_id" {
  description = "The ID of the GCP project where resources will be created."
  type        = string
  nullable    = false
}

variable "region" {
  description = "The region where resources will be created."
  type        = string
  nullable    = false
}

variable "client_email" {
  description = "Terraform Service Account Client Email"
  type        = string
  nullable    = false
}

variable "tfstate_bucket_name" {
  description = "Autogenerated bucket name for storing terraform state"
  type        = string
  nullable    = false
}

